version: "3"
services:
  web:
    build:
      context: ./fastapi_app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./data:/data
    networks:
      - sim_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - sim_network

  redis:
    image: redis:7
    networks:
      - sim_network

  example_worker:
    build:
      context: ./task_queue
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./data:/data
    networks:
      - sim_network

  mosaik-orbit:
    image: registry.gitlab.com/mosaik/mosaik-gui/backend:99-build-and-push-docker-images
    expose:
      - "${MOSAIK_ORBIT_PORT:-8442}"
    environment:
      - MOSAIK_ORBIT_HOST=${MOSAIK_ORBIT_HOST:-0.0.0.0}
      - MOSAIK_ORBIT_PORT=${MOSAIK_ORBIT_PORT:-8442}
    networks:
      - sim_network

  mosaik-gui:
    image: registry.gitlab.com/mosaik/mosaik-gui/frontend:99-build-and-push-docker-images
    ports:
      - "0.0.0.0:${FRONTEND_HOST_PORT:-8080}:80"
    depends_on:
      - mosaik-orbit
    networks:
      - sim_network
    environment:
      - MOSAIK_ORBIT_PROXY_HOST=${MOSAIK_ORBIT_PROXY_HOST:-mosaik-orbit}
      - MOSAIK_ORBIT_PORT=${MOSAIK_ORBIT_PORT:-8442}

  mosaik-worker:
    build:
      context: .
      dockerfile: mosaik/mosaik-worker/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - MOSAIK_WS_URL=ws://mosaik-orbit:8442
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    depends_on:
      - redis
      - rabbitmq
      - mosaik-orbit
    volumes:
      - ./data:/data
    networks:
      - sim_network

networks:
  sim_network:
