CXX ?= g++

CPPBASE_DIR ?= /build/CppBaseWrapper
SRC_DIR := src
OBJ_DIR := obj
TARGET := SumoWrapper

CPPFLAGS := \
	-I$(SRC_DIR) \
	-I$(CPPBASE_DIR)/src \
	-I/usr/local/include/librdkafka \
	-I$(SUMO_HOME)/include
CXXFLAGS := -fPIC -DRTI_USES_STD_FSTREAM -fpermissive -std=c++17 -w -O2
LDFLAGS := -L$(CPPBASE_DIR)/lib -L/usr/local/lib -L$(SUMO_HOME)/lib -pthread
LDLIBS := -lsimwrapper -lpugixml -lsumocpp -ltracicpp -ljansson

SRCS := \
	$(SRC_DIR)/PrepareRun.cpp \
	$(SRC_DIR)/SimulationEventEmitter.cpp \
	$(SRC_DIR)/SumoWrapper.cpp \
	$(SRC_DIR)/api/InteractionImpl.cpp \
	$(SRC_DIR)/api/OrchestrationImpl.cpp \
	$(SRC_DIR)/api/ProvisionImpl.cpp \
	$(SRC_DIR)/api/SumoConnectionLibSUMO.cpp \
	$(SRC_DIR)/api/SumoObserver.cpp \
	$(SRC_DIR)/logic/SumoSimulationControl.cpp

OBJS := $(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS) $(LDLIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ_DIR) $(TARGET)
